services:
  kafka-0:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9097:9097"
      - "9095:9095"
    networks:
      - local
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
      - KAFKA_CFG_KRAFT_MODE=true
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9095,CONTROLLER://:9093, EXTERNAL://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9095, EXTERNAL://localhost:9097
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  
  kafka-1:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9096:9096"
      - "9098:9098"
    networks:
      - local
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093
      - KAFKA_CFG_KRAFT_MODE=true
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9093, EXTERNAL://:9098
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9096, EXTERNAL://localhost:9098
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT


  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Dockerfile для app.py
    ports:
      - "8501:8501"
    networks:
      - local

    depends_on:
      - kafka-0
      - kafka-1

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter  # Dockerfile для Jupyter
    ports:
      - "8888:8888"
    networks:
      - local
    depends_on:
      - kafka-0
      - kafka-1

  model:
      build:
        context: .
        dockerfile: Dockerfile.model  # Dockerfile для model.py
      ports:
        - "10000:10000"
      networks:
        - local

      depends_on:
        - kafka-0
        - kafka-1


networks:
  local:
    driver: bridge